### ISSUE TITLE
Pretrained model file

### ISSUE THREAD

**Issue by Younghoon-Lee** [wilile26811249/MobileViT#3]
I appreciate your effort. It helps me a lot :)

It would be very helpful if you could share the pretrained model file for XS or XXS.

thank you,

**Comment by wilile26811249** [comment]
Yes, no problem.
But I had not trained the xs or xxs version of the model in the past.
I will provide the xxs version weights in a few days, because I need few days to train the model.

**Comment by Younghoon-Lee** [comment]
Thank you I am looking forward to it :)
